# School classes configuration

[[classes]]
name = "Discord Bot"
mentor = 1
slack: ""
room = "Valorant"
students = 

[[classes]]
name = "Spud Buds"
teacher = "Not Smith"
room = "OpenCV"
students = 23

[[classes]]
name = "MortalFoes"
teacher = "Evil Smith"
room = "Minecraft"
students = ["Wes", "Adrian"]
