# School classes configuration

[[classes]]
name = "Discord Bot"
teacher = "Smith"
room = "Valorant"
students = ["Gavin", "Disc", "Wendy"]

[[classes]]
name = "Spud Buds"
teacher = "Not Smith"
room = "OpenCV"
students = 23

[[classes]]
name = "MortalFoes"
teacher = "Evil Smith"
room = "Minecraft"
students = ["Wes", "Adrian"]
