# School classes configuration

[[classes]]
name = "Discord Bot"
mentor = 1
slack = ""
students = 20

[[classes]]
name = "Spud Buds"
mentor = 1
slack = "C098XJU0SEQ"
students = 20

[[classes]]
name = "MortalFoes"
mentor = 1
slack = ""
students = 20
