# School classes configuration

[[groups]]
name = "Discord Bot"
mentor = 1
slack = ""
text_channels = ""
voice_channels = ""
students = 20

[[groups]]
name = "Spud Buds"
mentor = 1
slack = "C098XJU0SEQ"
students = 20

[[groups]]
name = "MortalFoes"
mentor = 1
slack = ""
students = 20
